CREATE TABLE IF NOT EXISTS tu_customer_dialogue (
    id VARCHAR(32) PRIMARY KEY,
    category VARCHAR(100) DEFAULT '默认' COMMENT '分类',
    question VARCHAR(500) NOT NULL COMMENT '场景/提问描述',
    reply TEXT NOT NULL COMMENT '客服回复内容',
    image_url VARCHAR(500) DEFAULT NULL COMMENT '图片URL',
    sort_order INT DEFAULT 0 COMMENT '排序数字，越小越靠前',
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='客服对话模板';
