CREATE TABLE IF NOT EXISTS tu_llm_config (
    id INT AUTO_INCREMENT PRIMARY KEY,
    provider VARCHAR(20) NOT NULL COMMENT '提供商: kimi/minimax',
    api_key VARCHAR(255) DEFAULT NULL COMMENT 'API Key',
    model VARCHAR(50) DEFAULT NULL COMMENT '模型名称',
    is_active TINYINT DEFAULT 0 COMMENT '是否当前选中: 0=否 1=是',
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    UNIQUE KEY uk_provider (provider)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='大模型配置表';
